sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t mindaras/docker-travis-aws-sample -f Dockerfile.dev .

script:
  - docker run -e CI=true mindaras/docker-travis-aws-sample npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-travis-aws-sample"
  env: "Dockertravisawssample-env"
  bucket_name: "elasticbeanstalk-eu-central-1-522714423525"
  bucket_path: "docker-travis-aws-sample"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
